### PR TITLE
Updated Fast Money to more accurately reflect tv show

### PR DESCRIPTION
**Pull request by theredwillow**
Updated the Final Rounds to more accurately reflect the way that the game is played.

Video from gameshow for reference https://www.youtube.com/watch?v=-6VrbRxYems

1. Previous version used to show two columns during first final round. Reduced down to one.
1. Answer with 0 survey results is now a dropdown option and is the default
1. Question buttons have been moved to relevant locations (i.e. next to their input/select)
1. The "Wrong" sound has been updated to the right sound from the show (a long low-pitched buzz, not 3x high-pitched buzzes)
1. Final round 2 now displays as one column as well, until the admin hits the "Reveal First Round Answers" button
1. The partner's answer is now included on the Final Round 2 admin page
1. An "Already Answered" button has been created for duplicate answers, including the show's sound
1. Added localization variables where necessary using Google Translate

old-round-one-question
*Previous Round 1 Question Layout*

new-round-one-question
*Updated Round 1 Question Layout*

new-round-two-question
*Updated Round 2 Question Layout, with partner's answer and Duplicate buzzer*

single-column-board
*New single column layout, for first round and first half of second round*

Note
Massive file count is only because JSON files needed to be updated to reflect new default state of questions. See first commit if clutter is overwhelming.
Also see new reported issue https://github.com/joshzcold/Cold-Family-Feud/issues/73

Code cleanup
1. Removed some unused imports
1. Changed a javascript variable's snake_case to camelCase
1. Added keys to mapping functions, per React's documentation suggestions. Reduces console erroring. https://legacy.reactjs.org/docs/lists-and-keys.html#keys
1. Reformated ternary render:null's to simple conditional rendering
1. Fixed a class -> className, per React

Known bugs
1. The bug where the question score is `revealed` as 0 instead of left empty before the "Submit/Award Points" button persists
1. The bug where the fast money rewarded points sound is not the "bong" sound from the show persists

### CODE REVIEW

**Comment by joshzcold** [comment]
I like the changes. 
Do you feel adding `selection : -1` to all the game files might make this issue harder to complete?
https://github.com/joshzcold/Cold-Family-Feud/issues/73

I guess in "game load" we will just have loop through the rounds at set the correct state data no matter what that is.

I'll see about give this PR a try soon.
Thank you.

**Comment by joshzcold** [comment]
I tried your changes and everything is working well 👍

Can I ask that the "Partner's Answer" test is stylized to be a bit bigger to fit with the buttons and has the `theme`'s secondary color so it shows up on the dark theme? Something like `text-secondary-XXX` 

For how big I would suggest going into mobile view in chrome/firefox dev tools and see if you can still read it.

image

**Review by joshzcold — CHANGES_REQUESTED** [review]
See last comment

**Comment by theredwillow** [comment]
Fair ask. I was knee-deep in logic when I made this but it should've been a FIXME.

Added classes `text-foreground text-3xl p-5`.

For reference, its sibling button has the classes `border-4 rounded p-5 text-2xl flex-grow bg-secondary-300 text-foreground`.

default-theme
*default theme*

dark-theme
*dark theme*

slate-theme
*slate theme*

educational-theme
*educational theme*

**Comment by theredwillow** [comment]
I couldn't with that alignment... added `align-middle` too

Tried adding `text-center` too, but it was ugly with "(No Answer)". Left it left-aligned.

image

**Review by joshzcold — APPROVED** [review]

**Comment by joshzcold** [comment]
Looks good, thank you 👍

**Comment by joshzcold** [comment]
This has been deployed to https://famf.app

Ill be looking to pick up this issue myself, so I can get changes out to production sooner.
Currently have to wait until no one is playing the game.
https://github.com/joshzcold/Cold-Family-Feud/issues/79

**Pull request merged**
