### PR TITLE
Create more space for q's on new page

### PR DESCRIPTION
**Pull request by theredwillow**
As is, users may feel frustrated that they can't see their questions on the /new page.
current-version-01-26-2024

I introduce new tailwind classes that allow the user to easily see what they have wrote.
new-version-01-26-2024

### CODE REVIEW

**Comment by joshzcold** [comment]
Looks good thank you 👍

**Comment by theredwillow** [comment]
Thank you for your prompt action!

I like to create dead simple MR's to check how active the owner is before coding too much. If you have any guidance on code uniformity/preferences that might make upcoming MR's more palatable, please feel free to reach out. (For example, I see you're using Tailwind, so I used that here.)

**Comment by joshzcold** [comment]
Format your code with `prettier`.

If you make new elements try to use colors that are already registered in the tailwind theme config.

The project is JavaScript, don't add typescript unless we convert everything to typescript.

New text elements get a translation function around the text. 
I wouldn't say you have to translate everything for the current languages if you do add something. I do have a script in the repo that can automatically do the language look ups in Google translate.

I appreciate the GitHub issues 👍

**Comment by theredwillow** [comment]
Changes aren't live yet. Please redeploy to famf.app.

**Pull request merged**
