### PR TITLE
Add 2 more christmas themed games

### PR DESCRIPTION
**Pull request by JBaczuk**
Awesome app, nice work!

### CODE REVIEW

**Comment by joshzcold** [comment]
Love to see it ♥️ thank you. 
just in time for the holidays.

**Comment by joshzcold** [comment]
deployed to https://www.famf.app/ in case thats an easier way to play these games with your family.

**Comment by JBaczuk** [comment]
Thanks! I'm casting from chrome to a Chromecast, and I'm thinking it might be nice if there was a way to cast the audio (intro music) with the game screen. Right now it only plays on the host screen, so you have to use a different audio source...

**Comment by joshzcold** [comment]
https://github.com/joshzcold/Cold-Family-Feud/issues/46

**Pull request merged**
